theme = "nord"

[editor]
line-number = "relative"
mouse = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.whitespace]
newline = "none"
