[colors.primary]
background = '#14161b'
foreground = '#e0e2ea'

[colors.cursor]
text = '#14161b'
cursor = '#e0e2ea'

[colors.selection]
text = '#14161b'
background = '#2c2e33'

[colors.normal]
black   = '#2c2e33'
red     = '#a30202'
green   = '#b3f6c0'
yellow  = '#6b5300'
blue    = '#81a9c6'
magenta = '#9d81bb'
cyan    = '#128184'
white   = '#4f5258'

[colors.bright]
black   = '#2c2e33'
red     = '#ffc0b9'
green   = '#b3f6c0'
yellow  = '#fce094'
blue    = '#8cf8f7'
magenta = '#7f639b'
cyan    = '#007373'
white   = '#c4c6cd'


[terminal.shell]
program = "/usr/bin/fish"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
y = 2

[window.padding]
x = 2
y = 2

[keyboard] 
#https://alacritty.org/config-alacritty-bindings.html
bindings = [
{ key = "Tab", mods = "Control", action = "SelectNextTab" },
{ key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
#disable macos shit
{ key = "w", mods= "Command", action = "None"},
]

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal]

