vim.keymap.set('n', '<Leader>o', ':Files<CR>')
vim.keymap.set('n', '<Leader>e', ':Lexplore<CR>')
vim.keymap.set('n', '<Leader>b', ':Buffers<CR>')
vim.keymap.set('n', '<Leader>w', ':w!<CR>')
vim.keymap.set('n', '<Leader>d', ':bd<CR>')
vim.keymap.set('i', 'kj', '<ESC>')
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', 'k', 'gk')
vim.keymap.set('n', '<Leader>vd', 'lua vim.diagnostic.open_float()')
vim.keymap.set('n', '<C-u>', '<C-u>zz')
vim.keymap.set('n', '<C-d>', '<C-d>zz')
