[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.normal]
black = "#1e2132"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "0x161821"
foreground = "0xc6c8d1"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 2
y = 6

[selection]
save_to_clipboard = true

[window.padding]
x = 2
y = 2

[keyboard] 
#https://alacritty.org/config-alacritty-bindings.html
bindings = [
{ key = "Tab", mods = "Control", action = "SelectNextTab" },
{ key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
#disable macos shit
{ key = "w", mods= "Command", action = "None"},
]

[window]
decorations = "None"

[mouse]
hide_when_typing = true
